# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 11
        postgresql db: databasename-test
        postgresql user: dev
        postgresql password: dev
  
  deploy:  
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set QA Environment
        run: echo "::set-env name=ENVIRONMENT::qa"

      - name: Set Production Environment
        if: github.ref == 'refs/heads/master'
        run: echo "::set-env name=ENVIRONMENT::prod"

      - name: Configure Heroku
        run: heroku config:set GIT_HASH=${GITHUB_SHA} GIT_BRANCH=${GITHUB_REF} --app my-app-name-$ENVIRONMENT

      - name: Push to Heroku
        run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/my-app-name-$ENVIRONMENT.git $GITHUB_SHA:master

      - name: Run Database Migrations
        run: heroku run knex migrate:latest --app my-app-name-$ENVIRONMENT
